sudo: false
language: node_js
node_js:
  - "10.16.1"
env:
  - CXX=g++-5
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    firefox: "latest"
before_install:
  - yarn global add node-gyp
cache:
  yarn: true
branches:
  except: 
    - gh-pages
before_script:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
#  - yarn test
  - yarn build
deploy:
  - provider: npm
    skip_cleanup: true
    email: "reto@factsmission.com"
    api_key: $NPM_AUTH_TOKEN
    on:
      tags: true
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file: distribution/latest/ld2h.js
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: bash .travis_publish
    on:
      tags: true

  