sudo: false
language: node_js
node_js:
  - "6.1"
branches:
  only: 
    - gh-pages
    - /.*/ 
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
deploy:
  - provider: releases
    api_key:
      secure: "Be4zPXH/CKqtoXwNgm/Euzz1WooXKOWLj05KIBnoFXChpHrs62W05mdEUzRzkkbZIMvK+IYHLJXSlT+I0HID+yGGmxn3t83Ltyw/RgnhbW1TBT/bzQ9AtTjGxl69p5N0OgeRQlrQsjeyrEVoAxY6PB937WwIXxqJ45UOnJID1tnW3M7QP3UOvWb0SKbealsI0FSdPL0HHuG0ayvkTgM6zQHPjcmFenujrPhTgvs2d/ukZpj04XBmO2vl/apRFRHtr0QtYjiiXVZboa8v6mPdd0+SifmMOir6OfFdh55IuAn2rVJ70Tv8oWRw/TSDkKuW6hjFHj1zzM1eY6+oyQzlcAx9ySL6peseaA4e5qTic8rhTzjUfW+Nevdwp7ouIfQ6+11S6MVwnvbuxU+JgK4/Ph1b7L2cKJr2OmwLiCpOTuxRCanU0Mv846HRP2Bt90BfJdFREQEKk+HsGZEnqYqIqrp3Y1Xo212uWpCsbZ9UCM/8BAc9Kw1k1ZWHzeM5OVcFMPhwSNyky2IfOt2+f0Nt0/dyU3FPnW30CBOG5hIKC9re8r1Gxftj1LiKeyL54j9XNL7WZK2+rji3Yia4OfEEb+2Hy+MPFhZygQPhXDcXfRqZmMNFujohyFPq0vPz7fSMyoOhjnJJHLif5AC3FJJY9dteMcZQs8oMOx0N4Kh9cf0="
    file: dist/ld2h.js
    on:
      tags: true
  - provider: npm
    email: "reto.gmuer@zazuko.com"
    api_key:
      secure: "by26QWTeVgmtZ/uDE08MBu7lasKuKJKYu7ZXR2fdC4FboYbQr27V4WTIc4EJIjpWMul7V0bVVOCIjOFc90tOfh/RX/3TxELzkLhLkmFbXVgEM5Q+Qg7Ay2gms/Gto5ttxb2b7Z4vAV18oDjS5SY2+mveAPkQ5pkvO3V8DyF5hqornQK27tNDm/SDSxFz8Tvgk6edCq2OVbSLiw89Oukzm6WkNgw5N/otb0HSgeUKr9FleI+YDkEU4BmKYlA1vns9R37vdBS9bzEHlfmUhS2+kLbjYWkTyJHLole5ld6mig57SfrNRkZykP1wjrUU7zGqPlnyuUII1zL18YbH94H9TReHMZqQ63kgv2xYch2tCLTbT/w6ecw389MaYxKIU6VmBAoOvCAJ1zGk9BgQvzyQEpWP5gAPspHi4Rsebl9JBLSOofxOw1jqIIBVy20FZ06Rs8NbUhWpQ+hhJAwZwf5+56/w4HdWjnlUnkcx1yKSY06vuj9FcC5oV7cWlykeeqIvmeydBCqZwEjVgGQsefbbo0wLmu4y4w6nHFkisaHbMd2Xa/RMIe2V5m029yWs017iEPcFB1PZABsfMYfPiJ9JxJd6wKSOWmsx6eMN8lAGalq0/V0QBqUXxYVxlOojfNj5Z8UrQJOVkVwhcVmnF0KJ7VLWa4L3UVVADuazI5RL2wc="
    on:
      tags: true
  